### ISSUE TITLE
95% emitting unnamed compat pluginError: Unexpected Response: socket hang up

### ISSUE THREAD

**Issue by pouu69** [jscrambler/jscrambler#119]
I am using the following version. If you run the build locally, a socket hang up error occurs.

- jscrambler-webpack-plugin : v5.5.13
- jscrambler : 5.5.13

```
95% emitting unnamed compat pluginError: Unexpected Response: socket hang up
    at new ClientError (/Users/user/webdev2/bank/th-bank-webapp/node_modules/jscrambler-webpack-plugin/node_modules/jscrambler/dist/client.js:65:112)
    at /Users/user/webdev2/bank/th-bank-webapp/node_modules/jscrambler-webpack-plugin/node_modules/jscrambler/dist/client.js:297:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  statusCode: 500
```

in my config  (remove private info)

```
{
    enable: config.build.isJsc,
    keys: {
      accessKey: '',
      secretKey: '',
    },
    applicationId: '',
    params: [
      // optimization
      {
        name: 'whitespaceRemoval',
      },
      {
        name: 'identifiersRenaming',
        options: { mode: 'SAFEST' },
      },
      {
        name: 'deadCodeElimination',
      },
      {
        name: 'duplicateLiteralsRemoval',
      },
      {
        name: 'constantFolding',
      },
      // Obfuscation (Cost Low)
      {
        name: 'booleanToAnything',
      },
      {
        name: 'stringEncoding',
        options: {
          encoding: ['hexadecimal', 'unicode'],
        },
      },
      {
        name: 'propertyKeysObfuscation',
        options: {
          encoding: ['hexadecimal'],
        },
      },
      {
        name: 'regexObfuscation',
      },
      {
        name: 'domainLock',
        options: {
          domains: '',
          countermeasures: {
            customCallback: null,
            deleteCookies: true, // false
            redirect: null,
            breakApplication: false, // false
            realTimeNotifications: false,
            selfDestruct: false,
          },
        },
      },
    ],
    codeHardeningThreshold: 0,
    areSubscribersOrdered: false,
    applicationTypes: {
      webBrowserApp: false,
      desktopApp: false,
      serverApp: false,
      hybridMobileApp: true,
      javascriptNativeApp: false,
      html5GameApp: false,
    },
    languageSpecifications: {
      es5: true,
      es6: false,
      es7: false,
    },
    useRecommendedOrder: true,
    jscramblerVersion: '6.3',
    tolerateMinification: false,
    sourceMaps: false,
    host: '',
    basePath: '/api',
    port: '80',
  }
```

Why does a socket hang up occur?

**Comment by vitorveiga** [comment]
Hello, 

if the problem persists please get in touch with us at support@jscrambler.com

Best regards,
